### ISSUE TITLE
Is Efinity Software completely opensource? Or are there any other opensource toolchains for this Efinix Trion T8F81C FPGA ?

### ISSUE THREAD

**Issue by mikebdp2** [tommy-leung/FireAnt#1]
If no, this is a serious downside compared to other devboards based on Lattice FPGAs supported by the IceStorm opensource toolchain ( www.clifford.at/icestorm/ ).

**Comment by tommy-leung** [comment]
Efinity Software is not open sourced. However, it is well maintained by Efinity Development Team. And they keep enhancing the IDE and upgrading support to other devices for Trion series. I am sure you will find it easy to use.

**Comment by mikebdp2** [comment]
@tommy-leung Many people who visit Crowdsupply (including me) are trying to avoid the closed source proprietary software -  because it could contain the spying backdoors, low quality code and violates the freedoms of computing:
https://www.gnu.org/philosophy/free-sw.html

- The freedom to run the program as you wish, for any purpose (freedom 0).
- The freedom to study how the program works, and change it so it does your computing as you wish (freedom 1). Access to the source code is a precondition for this.
- The freedom to redistribute copies so you can help others (freedom 2).
- The freedom to distribute copies of your modified versions to others (freedom 3). By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

In example, Efinity might go bankrupt or get acquired by some larger company one day, and the people will be left with an unsupported product - with no possibility of bugs fixing and features addition to Efinity IDE since its' source code is closed. Not an unlikely scenario, considering a small size of Efinity company compared to i.e. Xilinx.

It really puzzles me why the small FPGA makers like Efinity can't just open their source code and share it with the community. It's not like Xilinx will steal their secrets from this open source: not just because it's illegal, but also since it's highly unlikely that a small FPGA maker could invent a more efficient algorithm than Xilinx with its' billions of dollars and huge workforce. Meanwhile, opening the source code delivers a huge competitive advantage in the eyes of freedom-caring people, who value their computing freedom more than a slightly better technical feature.

I sincerely hope that you could at least consider to either try to persuade Efinity into releasing the complete source code of their IDE _(under some freedom-respecting license like GPLv3)_ or to switch to Lattice supported by IceStorm for your future products. Otherwise you might be losing a significant part of market: your product has a good competitive advantage against the Lattice-based competitors _(mentioned at your CrowdSupply page at Comparison section)_ regarding the hardware, but loses greatly regarding the software - because no open source available for Efinity. This is the only reason why I cannot preorder your product at the moment.

**Comment by tommy-leung** [comment]
I agree with you that there are advantages for opensource software, nevertheless there are strategies or other concerns especially for running business like Xilinx, Altera or many other chip. Anyway, I'm not from Efinix and I cannot speak for them. Finally, thanks for your opinion. I've passed this message to Efinix Inc.

**Comment by avesus** [comment]
Time is ticking. I agree with all sides of this business, but it's 2021.
