### ISSUE TITLE
Source code for sobel filter

### ISSUE THREAD

**Issue by mwolak07** [tommy-leung/FireAnt#10]
I am a high school student looking to use FireAnt at an FPGA workshop for an upcoming hackathon. I wanted to demonstrate the Sobel filter example. Is there any way I could get the source code for this Sobel filter?

**Comment by tommy-leung** [comment]
@mwolak07 ,
I am really sorry for missing out your message. Can you send an email to fireant@jungle-elec.com for the video demo support?
