### ISSUE TITLE
no bin/source.bat in archive

### ISSUE THREAD

**Issue by Martoni** [tommy-leung/FireAnt#3]
In archive I downloaded there is no source.bat but source.sh in bin/ directory.

Maybe it a little mistake[ in the tutorial ](https://github.com/jungle-elec/FireAnt/wiki/Efinity-Software-Installation-Guide#command-line-scripting-setup-for-linux)?

**Comment by tommy-leung** [comment]
Hi @Martoni , Thanks for correcting me. The command should be:

> source bin/setup.sh
