### ISSUE TITLE
What is the input clock frequency ?

### ISSUE THREAD

**Issue by Martoni** [tommy-leung/FireAnt#4]
I can't find the clock frequency of PLL_IN clock for FireAnt kit.
I can see the crystal on schematic (Y1) but no mention of frequency.

**Comment by tommy-leung** [comment]
@Martoni , Thanks for pointing out the issue. I am sorry I didn't write it out explicitly in schematic and will update it accordingly. You can find out the input clock freq in [FireAnt.peri.xml](https://github.com/jungle-elec/FireAnt/blob/master/examples/FireAnt.peri.xml). The crystal frequency is 33.33MHz. Besides, you will find this file very useful as it defines all the hardware peripheral for FireAnt

**Comment by Martoni** [comment]
Thanks Tommy,

It's strange that we need xml file for pinout definition.
