### ISSUE TITLE
USB Backend Issue

### ISSUE THREAD

**Issue by jstwiddy** [tommy-leung/FireAnt#7]
I'm trying to go through the quickstart installation guide to get my FireAnt set up, and I'm running into an issue with step 6 of the USB driver installation.  I've downloaded Zadig and attempted to install libusbK as instructed (after confirming the USB ID is for the correct device - 0403 6014), but when I open the Efinity programmer I get the following error:

> ERROR: could not find USB backend, cannot perform any USB operations

with no further information.  I've tried searching for information on that error but wasn't able to find anything elsewhere online.  I went back to Zadig to try re-installing libusbK and I noticed that when I pull the device back up, it's detected driver is once again FTDIBUS, not libusbk, despite previously having received a message saying "The driver was installed successfully."  This happens every time I try reinstalling libusbK, leading me to believe this may be the source of the issue.  I've tried using both USB 2.0 and 3.0 ports without any difference, and I'm running Zadig as admin so I don't think that's the problem.

Versions are:
- Efinity/Efinity Programmer 2019.2.192
- Zadig 2.4
- libusbK v3.0.7.0

I've attached screengrabs of the relevant errors.  Any help you can give would be appreciated.
![FireAnt_error_1](https://user-images.githubusercontent.com/58098380/69472827-dcd0d200-0d7c-11ea-81ac-f5ca69213142.png)
![FireAnt_error_2](https://user-images.githubusercontent.com/58098380/69472829-e0645900-0d7c-11ea-8271-b6b5003f5fb0.png)

**Comment by tommy-leung** [comment]
Hi @jstwiddy ,

May I know more about your environment like your Windows version, architecture (32/64-bit). Besides, for instance, could you try with another PC for quick trial?

**Comment by jstwiddy** [comment]
Hello @tommy-leung ,

Thanks for the response.  I've tried the process again with another computer and I'm getting the same result (libusbK installation is reported successful but the error in Efinity Programmer still persists).  I've tried multiple times with both computers, and sometimes it will say "libusbK" as the currently installed driver after plugging it back in, but not every time.

The two computers are Windows 8.1 Pro and Windows 7, respectively - both are 64 bit (IIRC the Zadig utility doesn't have 32 bit support anyway).  At this point, I'm not sure how to determine if the issue is Zadig, the FTDI chip, or the Efinity application (or some combination).  Is there another libusbK installation utility I could try for a point of comparison?

I'm going to try on a third computer tomorrow and see if that has any effect.

**Comment by tommy-leung** [comment]
Hi @jstwiddy 

There is another method to install libusbK, not sure it works for you.

Step 1: download _libusbK-3.0.7.0-setup.exe_ in [https://sourceforge.net/projects/libusbk/](https://sourceforge.net/projects/libusbk/)

Step 2: Install The UsbK Development Kit with all default settings except this:
![image](https://user-images.githubusercontent.com/48233410/69662053-9520b200-10be-11ea-8318-785351af1163.png)
Check the _Create and install a libusb-win32 device driver a package_ option

Step 3: Continue the installation. When InfWizard pop-up, choose _libusbK v3.0.7.0 (04/28/2014)_
![image](https://user-images.githubusercontent.com/48233410/69662268-fc3e6680-10be-11ea-8fb4-3f60e54c6538.png)
and Click Next

Step 4: Plug-in FireAnt and choose _Show All Devices_ , you should be seeing a FTDIBUS device as below, select it and click Next:
![image](https://user-images.githubusercontent.com/48233410/69662491-6d7e1980-10bf-11ea-9cce-d3e576dc2d81.png)

Step 5: Continue the InfWizard until Complete Message shown. *DON'T* click Finish. Instead, click on _Finish & Install Driver Now_
![image](https://user-images.githubusercontent.com/48233410/69662778-f6955080-10bf-11ea-97f7-5d211354de14.png)

Step 6: Device Driver Installation Wizard will complete the driver installation. After that, you should be seeing a _libusbK Usb Devices_ in Device Manager
![image](https://user-images.githubusercontent.com/48233410/69662905-30feed80-10c0-11ea-8197-f8464cee1b9f.png)

Hope this method works for you

**Comment by jstwiddy** [comment]
Hey @tommy-leung,

I haven't tried your alternate libusbK installation method, but I was able to get both the driver and the Efinity programmer to work on a different computer.  However, I've now tried to open the same device using Efinity on the original computer I tested, and  I'm still seeing the USB error.  The fact that it worked and I was able to program the blink program on a different system indicates to me that the correct driver has been installed, and the issue seems to be with Efinity itself.  I'm going to try reinstalling that program to see if that fixes the issue - I'll update when that's done.

**Comment by jstwiddy** [comment]
Still getting the same issue, unfortunately.  I was also able to confirm that my system recognizes the device as running libusbK, since I can see "libusbK USB Devices" and "Single RS232-HS" in my device manager, so this seems to be solely an Efinity issue.  Should I contact their support team directly to try and figure out what's going on?

Thanks,

Jack

**Comment by tommy-leung** [comment]
Hi Jack,

Great thanks for your feedback which also help us to improve. It looks like a compatibility issue for You can always post issue on Efinix Support Center. I will also report the problem to their support team and hope to they have a quick fix for you.

**Comment by sammhho** [comment]
Hi @jstwiddy ,
This is Sam from SW at Efinix, thx for trying our tool!
What you're seeing is the Python "pyftdi" module trying to talk to a libusb backend (thru "usb" module) but failed to find any, which could indicate a driver or an environment path problem.

In case you're familiar with Python and have a stand-alone Python installed on that machine, 
you can try (you'll need to have pyftdi installed in advance, by doing `pip install pyftdi`): 
`python -c "from pyftdi.ftdi import Ftdi; Ftdi.find_all([(0x0403,0x6010), (0x0403,0x6014)])"` 
and see if it reads the usb stack successfully.
