### ISSUE TITLE
Camera adapt reference for sobel filter manipulation

### ISSUE THREAD

**Issue by Martoni** [tommy-leung/FireAnt#8]
Hi is it possible to have the reference for the  camera module OV5640 adapt used in [this demo](https://www.crowdsupply.com/xips-technology/fireant/updates/awesome-sobel-filter-demo-with-fireant) ?

I managed to find the camera but not the board adapt.

Thanks

**Comment by tommy-leung** [comment]
@Martoni 

Do you mean the source of purchase? Originally, I purchased this camera module in [Taobao](https://detail.tmall.com/item.htm?spm=a1z10.5-b-s.w4011-21725054633.47.fec84eb4xHPwKO&id=596445651452&rn=4b5f47aac7d2825708b62aafa827f2f2&abbucket=17) for testing.

![](https://img.alicdn.com/imgextra/i4/68209436/TB2c4Dzl30kpuFjSspdXXX4YXXa_!!68209436.jpg)

I will try to find alternative in Amazon or EBay or other website for your reference

**Comment by Martoni** [comment]
> Do you mean the source of purchase?

Yes exactly.

> I will try to find alternative in Amazon or EBay or other website for your reference

Thanks a lot ! It seems to be difficult for an european to purchase on taobao ;)

**Comment by Martoni** [comment]
Have you find alternative ?

**Comment by tommy-leung** [comment]
@martoni,

Sorry, We haven't sort it out. For instance, do you mind if we purchase the exact module in [Taobao](https://detail.tmall.com/item.htm?spm=a1z10.5-b-s.w4011-21725054633.47.fec84eb4xHPwKO&id=596445651452&rn=4b5f47aac7d2825708b62aafa827f2f2&abbucket=17) and ship to you?

**Comment by Martoni** [comment]
@tommy-leung ,

You can do that ? I'm interested yes !
I can't find your email to contact you directly. Mine is not secret : mail@fabienm.eu
